version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=Hoanghandsome1
      - MYSQL_DATABASE=e_learning_dev
    ports:
      - 3308:3306
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: .
    restart: always
    env_file: ./.env
    ports:
      - 5000:5000

volumes:
  db:
