version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env # Load environment variables from a file if needed
    environment:
      MYSQL_DATABASE: e_learning_dev
      MYSQL_ROOT_PASSWORD: Hoanghandsome1
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  app:
    depends_on:
      - mysqldb
    build: .
    restart: always
    env_file: ./.env # Load environment variables from a file if needed
    ports:
      - 80:5000

volumes:
  db:
