import userRouter from './userRoutes';
import videoRouter from './videoRoutes';
import courseRouter from './courseRoutes';
import lessonRouter from './lessonRoutes';
import conversationRouter from './conversationRoutes';
const express = require('express');
const routers = express.Router();
routers.use(userRouter);
routers.use(videoRouter);
routers.use(courseRouter);
routers.use(lessonRouter);
routers.use(conversationRouter);
export default routers;
